// <auto-generated />
using Deco.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deco.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240109163624_AddAndSeedProducts")]
    partial class AddAndSeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deco.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Picture"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Carpet"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Cabinet"
                        });
                });

            modelBuilder.Entity("Deco.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("SetPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Drawn by Van Goh",
                            Name = "Stary Night",
                            Price = 55000.0,
                            SetPrice = 45000.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Famous screaming person",
                            Name = "Scream",
                            Price = 65000.0,
                            SetPrice = 55000.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fox fur carpet 8*5M",
                            Name = "Fox fur 8*5",
                            Price = 3500.0,
                            SetPrice = 3000.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bear fur carpet 9*10M",
                            Name = "Bear fur 9*10",
                            Price = 5000.0,
                            SetPrice = 4000.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "White Cabinet 170*40*70",
                            Name = "Tall White Cab170",
                            Price = 6000.0,
                            SetPrice = 5000.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Dark Cabinet 45*40*70",
                            Name = "Short Dark Cab45",
                            Price = 2000.0,
                            SetPrice = 1000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
